export const expenses = [
  'Expenses:Food',
  'Expenses:Food:Coffee',
  'Expenses:Life',
  'Expenses:Clothing',
  'Expenses:Transport',
  'Expenses:Productivity',
  'Expenses:Health:Medical',
  'Expenses:Health:FoodSupplements',
  'Expenses:Sport',
  'Expenses:Sport:Gym',
  'Expenses:Sport:Climbing',
  'Expenses:Podcast',
  'Expenses:Relationships:Partner',
  'Expenses:Entertainment',
];
